"""Emit the final processed CSV + a short data-quality report (M3.3).

Flattens the normalized paper records (nested authors/topics/references) into a
one-row-per-paper table for `data/processed/clean_papers.csv`, and writes a
human-readable data-quality report alongside it.

Multi-valued cells (authors, institutions, topics, references) are joined with
" | " -- pandas quotes any cell that contains the CSV delimiter, so names with
commas survive a round-trip. The nested JSONL stays the source of truth for the
graph/vector builders; this CSV is the inspectable, shareable artifact.

    python src/ingest/export.py

Reads:  data/interim/papers_normalized.jsonl  (M3.2)
Writes: data/processed/clean_papers.csv
        data/processed/data_quality_report.md
"""

from __future__ import annotations

import json
import os
import sys

import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import config  # noqa: E402

SEP = " | "  # multi-value cell separator


def _join(values) -> str:
    return SEP.join(str(v) for v in values)


def flatten(rec: dict) -> dict:
    """One nested paper record -> one flat CSV row."""
    authors = rec.get("authors") or []
    topics = rec.get("topics") or []
    refs = rec.get("references") or []

    # Institutions are nested under authors; collapse to distinct, order-preserved.
    inst_ids, inst_names, seen_i = [], [], set()
    for au in authors:
        for inst in au.get("institutions") or []:
            iid = inst["inst_id"]
            if iid not in seen_i:
                seen_i.add(iid)
                inst_ids.append(iid)
                inst_names.append(inst["name"])

    topic_fields, seen_f = [], set()
    for tp in topics:
        f = tp.get("field")
        if f and f not in seen_f:
            seen_f.add(f)
            topic_fields.append(f)

    return {
        "paper_id": rec["paper_id"],
        "title": rec["title"],
        "abstract": rec["abstract"],
        "has_abstract": rec["has_abstract"],
        "year": rec["year"],
        "cited_by_count": rec["cited_by_count"],
        "n_authors": len(authors),
        "author_ids": _join(a["author_id"] for a in authors),
        "author_names": _join(a["name"] for a in authors),
        "n_institutions": len(inst_ids),
        "institution_ids": _join(inst_ids),
        "institution_names": _join(inst_names),
        "n_topics": len(topics),
        "topic_ids": _join(t["topic_id"] for t in topics),
        "topic_names": _join(t["name"] for t in topics),
        "topic_fields": _join(topic_fields),
        "n_references": len(refs),
        "reference_ids": _join(refs),
    }


def build_report(records: list[dict], df: pd.DataFrame) -> str:
    """Render a short markdown data-quality report from the records + flat table."""
    n = len(df)

    def pct(count: int) -> str:
        return f"{count:,} / {n:,} ({100 * count / n:.1f}%)" if n else "0"

    # Distinct entity cardinalities (from nested records).
    authors, insts, topics, fields = set(), set(), set(), set()
    cites_edges = 0
    for rec in records:
        for au in rec["authors"]:
            authors.add(au["author_id"])
            for inst in au["institutions"]:
                insts.add(inst["inst_id"])
        for tp in rec["topics"]:
            topics.add(tp["topic_id"])
            if tp.get("field"):
                fields.add(tp["field"])
        cites_edges += len(rec["references"])

    years = df["year"].dropna().astype(int)
    by_year = years.value_counts().sort_index()
    year_lines = "\n".join(f"| {y} | {c:,} |" for y, c in by_year.items())

    cited = df["cited_by_count"].dropna().astype(int)

    lines = [
        "# Data-Quality Report — clean_papers.csv",
        "",
        "> Generated by `src/ingest/export.py` (M3.3) from "
        "`data/interim/papers_normalized.jsonl`.",
        "",
        f"**Papers (rows):** {n:,}  |  **distinct paper ids:** "
        f"{df['paper_id'].nunique():,}  |  **duplicate ids:** "
        f"{n - df['paper_id'].nunique()}",
        "",
        "## Field completeness",
        "",
        "| Field | Non-empty |",
        "| --- | --- |",
        f"| title | {pct(int((df['title'].str.len() > 0).sum()))} |",
        f"| abstract (real, not title fallback) | {pct(int(df['has_abstract'].sum()))} |",
        f"| publication_year | {pct(int(df['year'].notna().sum()))} |",
        f"| cited_by_count | {pct(int(df['cited_by_count'].notna().sum()))} |",
        f"| >=1 author | {pct(int((df['n_authors'] > 0).sum()))} |",
        f"| >=1 institution | {pct(int((df['n_institutions'] > 0).sum()))} |",
        f"| >=1 topic | {pct(int((df['n_topics'] > 0).sum()))} |",
        f"| >=1 in-corpus citation | {pct(int((df['n_references'] > 0).sum()))} |",
        "",
        "## Entity cardinalities (graph nodes/edges)",
        "",
        f"- **Authors (distinct):** {len(authors):,}",
        f"- **Institutions (distinct):** {len(insts):,}",
        f"- **Topics (distinct):** {len(topics):,}",
        f"- **Topic fields (distinct):** {len(fields):,}",
        f"- **CITES edges (in-corpus):** {cites_edges:,}",
        "",
        "## Distributions",
        "",
        f"- **Year range:** {int(years.min())}–{int(years.max())}",
        f"- **cited_by_count:** min {int(cited.min())}, "
        f"median {int(cited.median())}, mean {cited.mean():.1f}, "
        f"max {int(cited.max()):,}",
        f"- **Authors per paper:** min {int(df['n_authors'].min())}, "
        f"median {int(df['n_authors'].median())}, max {int(df['n_authors'].max())}",
        "",
        "### Papers per year",
        "",
        "| Year | Papers |",
        "| --- | --- |",
        year_lines,
        "",
        "## Known limitations",
        "",
        "- Abstracts fall back to the title when missing; `has_abstract=False` "
        "marks those rows (see M3.1).",
        "- CITES is intentionally in-corpus only (no backfill) — citation graph is "
        "sparse by design (CLAUDE.md §10).",
        "- Nested authors/topics/references live in the JSONL; the CSV joins them "
        "with `\" | \"` for inspection.",
        "",
    ]
    return "\n".join(lines)


def export(in_path: str, csv_path: str, report_path: str) -> dict:
    with open(in_path, encoding="utf-8") as fh:
        records = [json.loads(line) for line in fh if line.strip()]

    df = pd.DataFrame(flatten(r) for r in records)

    os.makedirs(os.path.dirname(csv_path), exist_ok=True)
    df.to_csv(csv_path, index=False, encoding="utf-8")

    report = build_report(records, df)
    with open(report_path, "w", encoding="utf-8") as out:
        out.write(report)

    return {
        "papers": len(df),
        "columns": df.shape[1],
        "csv": csv_path,
        "report": report_path,
    }


def main() -> int:
    in_path = os.path.join(config.DATA_INTERIM, "papers_normalized.jsonl")
    csv_path = os.path.join(config.DATA_PROCESSED, "clean_papers.csv")
    report_path = os.path.join(config.DATA_PROCESSED, "data_quality_report.md")
    if not os.path.exists(in_path):
        print(f"missing {in_path} -- run src/ingest/normalize.py first", file=sys.stderr)
        return 1
    stats = export(in_path, csv_path, report_path)
    print(f"Wrote {stats['papers']} rows x {stats['columns']} cols -> {stats['csv']}")
    print(f"Wrote data-quality report            -> {stats['report']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
